# Generated by Django 5.2.7 on 2026-07-06 16:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_seed_posts'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BugProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bug_id', models.CharField(choices=[('sqli', 'SQL Injection'), ('xss', 'Reflected XSS'), ('idor', 'IDOR'), ('file_upload', 'Unrestricted File Upload'), ('open_redirect', 'Open Redirect'), ('info_disclosure', 'Information Disclosure'), ('weak_crypto', 'Weak Password Storage')], max_length=20)),
                ('found_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'bug_id')},
            },
        ),
    ]
