# Generated by Django 5.2.7 on 2026-07-06 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_bugprogress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poc',
            name='content',
            field=models.FileField(blank=True, default='picpokcontent/default.png', upload_to='picpokcontent'),
        ),
    ]
