# Generated by Django 5.2.7 on 2026-07-06 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_poc_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poc',
            name='content',
            field=models.FileField(blank=True, default='picpokcontent/Google Dino Online.jpeg', upload_to='picpokcontent'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='picture',
            field=models.ImageField(default='profile_pictures/Google Dino Online.jpeg', upload_to='profile_pictures'),
        ),
    ]
